//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.9151
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDS_LIB
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SDS_user_data", Namespace="http://schemas.datacontract.org/2004/07/SDS_LIB")]
    public partial class SDS_user_data : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string EmailField;
        
        private string FirstNameField;
        
        private string LoginField;
        
        private string MasterField;
        
        private string PasswordField;
        
        private string PatronymicField;
        
        private string PhoneField;
        
        private string SecondNameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login
        {
            get
            {
                return this.LoginField;
            }
            set
            {
                this.LoginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Master
        {
            get
            {
                return this.MasterField;
            }
            set
            {
                this.MasterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Password
        {
            get
            {
                return this.PasswordField;
            }
            set
            {
                this.PasswordField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Patronymic
        {
            get
            {
                return this.PatronymicField;
            }
            set
            {
                this.PatronymicField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Phone
        {
            get
            {
                return this.PhoneField;
            }
            set
            {
                this.PhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SecondName
        {
            get
            {
                return this.SecondNameField;
            }
            set
            {
                this.SecondNameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SDS_user_sport_data", Namespace="http://schemas.datacontract.org/2004/07/SDS_LIB")]
    public partial class SDS_user_sport_data : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string ChestINField;
        
        private string ChestOUTField;
        
        private string ChestSTDField;
        
        private string DateField;
        
        private string GenderField;
        
        private string HeightField;
        
        private string HipsField;
        
        private string LoginField;
        
        private string SpecialGroupField;
        
        private string WaistField;
        
        private string WeightField;
        
        private string YearsField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChestIN
        {
            get
            {
                return this.ChestINField;
            }
            set
            {
                this.ChestINField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChestOUT
        {
            get
            {
                return this.ChestOUTField;
            }
            set
            {
                this.ChestOUTField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ChestSTD
        {
            get
            {
                return this.ChestSTDField;
            }
            set
            {
                this.ChestSTDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Gender
        {
            get
            {
                return this.GenderField;
            }
            set
            {
                this.GenderField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Height
        {
            get
            {
                return this.HeightField;
            }
            set
            {
                this.HeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Hips
        {
            get
            {
                return this.HipsField;
            }
            set
            {
                this.HipsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login
        {
            get
            {
                return this.LoginField;
            }
            set
            {
                this.LoginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SpecialGroup
        {
            get
            {
                return this.SpecialGroupField;
            }
            set
            {
                this.SpecialGroupField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Waist
        {
            get
            {
                return this.WaistField;
            }
            set
            {
                this.WaistField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Weight
        {
            get
            {
                return this.WeightField;
            }
            set
            {
                this.WeightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Years
        {
            get
            {
                return this.YearsField;
            }
            set
            {
                this.YearsField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SDS_user_additional_data", Namespace="http://schemas.datacontract.org/2004/07/SDS_LIB")]
    public partial class SDS_user_additional_data : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string DateField;
        
        private string GhenciField;
        
        private string KuperField;
        
        private string LoginField;
        
        private string Pulse_1minField;
        
        private string Pulse_20squatsField;
        
        private string Pulse_2minField;
        
        private string Pulse_3minField;
        
        private string StangeField;
        
        private string Step_pulseField;
        
        private string Step_pulse_2mField;
        
        private string Step_pulse_3mField;
        
        private string Stil_pulseField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ghenci
        {
            get
            {
                return this.GhenciField;
            }
            set
            {
                this.GhenciField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kuper
        {
            get
            {
                return this.KuperField;
            }
            set
            {
                this.KuperField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login
        {
            get
            {
                return this.LoginField;
            }
            set
            {
                this.LoginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pulse_1min
        {
            get
            {
                return this.Pulse_1minField;
            }
            set
            {
                this.Pulse_1minField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pulse_20squats
        {
            get
            {
                return this.Pulse_20squatsField;
            }
            set
            {
                this.Pulse_20squatsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pulse_2min
        {
            get
            {
                return this.Pulse_2minField;
            }
            set
            {
                this.Pulse_2minField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pulse_3min
        {
            get
            {
                return this.Pulse_3minField;
            }
            set
            {
                this.Pulse_3minField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Stange
        {
            get
            {
                return this.StangeField;
            }
            set
            {
                this.StangeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Step_pulse
        {
            get
            {
                return this.Step_pulseField;
            }
            set
            {
                this.Step_pulseField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Step_pulse_2m
        {
            get
            {
                return this.Step_pulse_2mField;
            }
            set
            {
                this.Step_pulse_2mField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Step_pulse_3m
        {
            get
            {
                return this.Step_pulse_3mField;
            }
            set
            {
                this.Step_pulse_3mField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Stil_pulse
        {
            get
            {
                return this.Stil_pulseField;
            }
            set
            {
                this.Stil_pulseField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SDS_user_normes", Namespace="http://schemas.datacontract.org/2004/07/SDS_LIB")]
    public partial class SDS_user_normes : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CrossField;
        
        private string DateField;
        
        private string Forward_bendField;
        
        private string JumpField;
        
        private string KettlebellField;
        
        private string LoginField;
        
        private string PressField;
        
        private string Pull_upField;
        
        private string Push_upsField;
        
        private string Run_100mField;
        
        private string SkiField;
        
        private string SwimmingField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Cross
        {
            get
            {
                return this.CrossField;
            }
            set
            {
                this.CrossField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Date
        {
            get
            {
                return this.DateField;
            }
            set
            {
                this.DateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Forward_bend
        {
            get
            {
                return this.Forward_bendField;
            }
            set
            {
                this.Forward_bendField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Jump
        {
            get
            {
                return this.JumpField;
            }
            set
            {
                this.JumpField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Kettlebell
        {
            get
            {
                return this.KettlebellField;
            }
            set
            {
                this.KettlebellField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login
        {
            get
            {
                return this.LoginField;
            }
            set
            {
                this.LoginField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Press
        {
            get
            {
                return this.PressField;
            }
            set
            {
                this.PressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Pull_up
        {
            get
            {
                return this.Pull_upField;
            }
            set
            {
                this.Pull_upField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Push_ups
        {
            get
            {
                return this.Push_upsField;
            }
            set
            {
                this.Push_upsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Run_100m
        {
            get
            {
                return this.Run_100mField;
            }
            set
            {
                this.Run_100mField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ski
        {
            get
            {
                return this.SkiField;
            }
            set
            {
                this.SkiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Swimming
        {
            get
            {
                return this.SwimmingField;
            }
            set
            {
                this.SwimmingField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="ISDS_service")]
public interface ISDS_service
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISDS_service/Registration", ReplyAction="http://tempuri.org/ISDS_service/RegistrationResponse")]
    bool Registration(SDS_LIB.SDS_user_data user);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISDS_service/Login", ReplyAction="http://tempuri.org/ISDS_service/LoginResponse")]
    bool Login([System.ServiceModel.MessageParameterAttribute(Name="login")] string login1, string password);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISDS_service/FindLogin", ReplyAction="http://tempuri.org/ISDS_service/FindLoginResponse")]
    bool FindLogin(string login);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISDS_service/ChangeUserData", ReplyAction="http://tempuri.org/ISDS_service/ChangeUserDataResponse")]
    bool ChangeUserData(SDS_LIB.SDS_user_data data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISDS_service/GetLastData", ReplyAction="http://tempuri.org/ISDS_service/GetLastDataResponse")]
    SDS_LIB.SDS_user_sport_data GetLastData(string login);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISDS_service/ChangeSportData", ReplyAction="http://tempuri.org/ISDS_service/ChangeSportDataResponse")]
    bool ChangeSportData(SDS_LIB.SDS_user_sport_data data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISDS_service/GetAllData", ReplyAction="http://tempuri.org/ISDS_service/GetAllDataResponse")]
    SDS_LIB.SDS_user_sport_data[] GetAllData(string login);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISDS_service/GetLastAdditionalData", ReplyAction="http://tempuri.org/ISDS_service/GetLastAdditionalDataResponse")]
    SDS_LIB.SDS_user_additional_data GetLastAdditionalData(string login);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISDS_service/ChangeAdditionalData", ReplyAction="http://tempuri.org/ISDS_service/ChangeAdditionalDataResponse")]
    bool ChangeAdditionalData(SDS_LIB.SDS_user_additional_data data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISDS_service/GetAllAdditionalData", ReplyAction="http://tempuri.org/ISDS_service/GetAllAdditionalDataResponse")]
    SDS_LIB.SDS_user_additional_data[] GetAllAdditionalData(string login);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISDS_service/GetLastNormes", ReplyAction="http://tempuri.org/ISDS_service/GetLastNormesResponse")]
    SDS_LIB.SDS_user_normes GetLastNormes(string login);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISDS_service/ChangeNormesData", ReplyAction="http://tempuri.org/ISDS_service/ChangeNormesDataResponse")]
    bool ChangeNormesData(SDS_LIB.SDS_user_normes data);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISDS_service/GetAllNormes", ReplyAction="http://tempuri.org/ISDS_service/GetAllNormesResponse")]
    SDS_LIB.SDS_user_normes[] GetAllNormes(string login);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISDS_service/GetMasters", ReplyAction="http://tempuri.org/ISDS_service/GetMastersResponse")]
    SDS_LIB.SDS_user_data[] GetMasters(string login);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISDS_service/GetMyData", ReplyAction="http://tempuri.org/ISDS_service/GetMyDataResponse")]
    SDS_LIB.SDS_user_data GetMyData(string login);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISDS_service/GetMyMaster", ReplyAction="http://tempuri.org/ISDS_service/GetMyMasterResponse")]
    SDS_LIB.SDS_user_data GetMyMaster(string login);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface ISDS_serviceChannel : ISDS_service, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class SDS_serviceClient : System.ServiceModel.ClientBase<ISDS_service>, ISDS_service
{
    
    public SDS_serviceClient()
    {
    }
    
    public SDS_serviceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public SDS_serviceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SDS_serviceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public SDS_serviceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public bool Registration(SDS_LIB.SDS_user_data user)
    {
        return base.Channel.Registration(user);
    }
    
    public bool Login(string login1, string password)
    {
        return base.Channel.Login(login1, password);
    }
    
    public bool FindLogin(string login)
    {
        return base.Channel.FindLogin(login);
    }
    
    public bool ChangeUserData(SDS_LIB.SDS_user_data data)
    {
        return base.Channel.ChangeUserData(data);
    }
    
    public SDS_LIB.SDS_user_sport_data GetLastData(string login)
    {
        return base.Channel.GetLastData(login);
    }
    
    public bool ChangeSportData(SDS_LIB.SDS_user_sport_data data)
    {
        return base.Channel.ChangeSportData(data);
    }
    
    public SDS_LIB.SDS_user_sport_data[] GetAllData(string login)
    {
        return base.Channel.GetAllData(login);
    }
    
    public SDS_LIB.SDS_user_additional_data GetLastAdditionalData(string login)
    {
        return base.Channel.GetLastAdditionalData(login);
    }
    
    public bool ChangeAdditionalData(SDS_LIB.SDS_user_additional_data data)
    {
        return base.Channel.ChangeAdditionalData(data);
    }
    
    public SDS_LIB.SDS_user_additional_data[] GetAllAdditionalData(string login)
    {
        return base.Channel.GetAllAdditionalData(login);
    }
    
    public SDS_LIB.SDS_user_normes GetLastNormes(string login)
    {
        return base.Channel.GetLastNormes(login);
    }
    
    public bool ChangeNormesData(SDS_LIB.SDS_user_normes data)
    {
        return base.Channel.ChangeNormesData(data);
    }
    
    public SDS_LIB.SDS_user_normes[] GetAllNormes(string login)
    {
        return base.Channel.GetAllNormes(login);
    }
    
    public SDS_LIB.SDS_user_data[] GetMasters(string login)
    {
        return base.Channel.GetMasters(login);
    }
    
    public SDS_LIB.SDS_user_data GetMyData(string login)
    {
        return base.Channel.GetMyData(login);
    }
    
    public SDS_LIB.SDS_user_data GetMyMaster(string login)
    {
        return base.Channel.GetMyMaster(login);
    }
}
